### ISSUE TITLE
jol installation

### ISSUE THREAD

**Issue by Mosko160** [artur-shaik/jc.nvim#11]
When I start nvim it ask to install jol, but got this result
![Screenshot from 2023-02-04 20-18-44](https://user-images.githubusercontent.com/96239214/216785908-a2637f35-ab5c-4232-828a-176f977a7b5a.png)

The configuration is
` require('jc').setup{}`
I'm on neovim 0.8.3 on POP_OS 22.04

**Comment by artur-shaik** [comment]
Do you have `JAVA_HOME` variable in your environment? Seems like it couldn't find jdk distribution.

**Comment by Mosko160** [comment]
I fix it but now I still have an error
![image](https://user-images.githubusercontent.com/96239214/216811730-71fc7641-e659-4f60-8ce8-68365993c967.png)

**Comment by artur-shaik** [comment]
You should try to install it yourself. Run this commands:

```
git clone https://github.com/openjdk/jol
cd jol
mvn install
```

**Comment by Mosko160** [comment]
I added this 
` <configuration><javadocExecutable>${java.home}/bin/javadoc</javadocExecutable></configuration>`
behind 
`<artifactId>maven-javadoc-plugin</artifactId>` 
and now it works
