### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by kuator** [artur-shaik/jc.nvim#2]
https://github.com/mfussenegger/nvim-jdtls

**Comment by artur-shaik** [comment]
As I became active java developer again, I of cause have tried that project as well as `coc-java`. But it couldn't fully satisfy my workflow. I had to run them along with `javacomplete2` so I can use functions of my old plugin.

Comparing to `nvim-jdtls` this project is not going to follow KISS principles.

**Comment by kuator** [comment]
Thank you for explanation!
