### ISSUE TITLE
Can not jump to definition of classes in JDK or jars.

### ISSUE THREAD

**Issue by qianwch** [artur-shaik/jc.nvim#3]
For example, pressing gd can not go to SpringApplication source.  No response...
```
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

}
```

**Comment by artur-shaik** [comment]
Can you check it now?

**Comment by qianwch** [comment]
It worked charmly! Now I am switching back from nvim-jdtls.

**Comment by qianwch** [comment]
Problem again, call "lua vim.lsp.buf.definition()" on library classes:
<img width="1274" alt="截屏2022-06-27 23 10 44" src="https://user-images.githubusercontent.com/45196316/175979889-aa0d80c7-df2d-40e7-83d1-8f3145c59301.png">

**Comment by qianwch** [comment]
Not a problem...
