### ISSUE TITLE
Error BufNewFile Auto-orders for "*":

### ISSUE THREAD

**Issue by JjersaR** [artur-shaik/jc.nvim#8]
Hello, today I opened a .java file and I got this error, the jdtls server is working correctly, do you know what I can do?
![image](https://user-images.githubusercontent.com/86206596/196984898-8e83a84e-e00f-4469-b382-6905192da030.png)

And the status of server jdtls:
![image](https://user-images.githubusercontent.com/86206596/196985131-29655734-4be7-4587-94b6-03f96d9b46af.png)

**Comment by artur-shaik** [comment]
Looks like you need install `nvim-lsp-installer` plugin.

**Comment by JjersaR** [comment]
If it was that, I download something that occupies the plugin and with that it was useful again, thank you for answering.

**Comment by artur-shaik** [comment]
So, did it solve your issue?

**Comment by JjersaR** [comment]
Yes, you solved it, thank you
